version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sentinel-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MULTIVERSX_API_URL=https://api.multiversx.com
      - MULTIVERSX_WS_URL=wss://gateway.multiversx.com/websocket
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sentinel-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped